name: Bump

on:
  push:
    branches:
      - 'main'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump
        run: bash scripts/bump_version.sh '${{ github.event.head_commit.message }}'

      - name: Get version
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Commit
        env:
          CI_COMMIT_AUTHOR: bump_bot
          VERSION: ${{ steps.get-version.outputs.version }}
        run: |
          git add package.json
          git config --global user.name '${{ env.CI_COMMIT_AUTHOR }}'
          git config --global user.email '${{ env.CI_COMMIT_AUTHOR }}@users.noreply.github.com'
          git commit -m "bump version to ${{ env.VERSION }} [skip actions]"
          git push origin main