name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint
