name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org' # need this to properly config credentials
          cache: 'yarn'

      - name: Commit
        env:
          CI_COMMIT_AUTHOR: bump_bot
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git add README.md
          git config --global user.name '${{ env.CI_COMMIT_AUTHOR }}'
          git config --global user.email '${{ env.CI_COMMIT_AUTHOR }}@users.noreply.github.com'
          git commit -m "bump version to $VERSION"
          git push origin main

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
