name: Update readme npm badge

on:
  workflow_run:
    workflows: [Publish]
    types:
      - completed

jobs:
  update-badge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'

      - name: Update badge
        run: bash scripts/update_badge.sh

      - name: Commit
        env:
          CI_COMMIT_AUTHOR: bump_bot
        run: |
          git add README.md
          git config --global user.name '${{ env.CI_COMMIT_AUTHOR }}'
          git config --global user.email '${{ env.CI_COMMIT_AUTHOR }}@users.noreply.github.com'
          git commit -m "update badge [skip actions]"
          git push origin main
