name: Validate PR title

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate PR title
        run: bash scripts/validate_title.sh '${{ github.event.pull_request.title }}'
